import DistanceAndDirectionLesson from "./lessons/DistanceAndDirectionLesson";
import CoordinateCalculationLesson from "./lessons/CoordinateCalculationLesson";
import ErrorAndEquipmentLesson from "./lessons/ErrorAndEquipmentLesson";
import FieldWorkflowLesson from "./lessons/FieldWorkflowLesson";
import HeightDifferenceLesson from "./lessons/HeightDifferenceLesson";
import LevelingBasicsLesson from "./lessons/LevelingBasicsLesson";
import ObservationErrorLesson from "./lessons/ObservationErrorLesson";
import PointAndPositionLesson from "./lessons/PointAndPositionLesson";
import TotalStationLesson from "./lessons/TotalStationLesson";
import type { BasicsLessonDefinition } from "./types";

export const basicsLessons = [
  {
    id: "point-and-position",
    number: "01",
    title: "測量の全体像と測点",
    description: "求める成果から測量を選び、測点の役割と成果までの流れを学ぶ",
    learningGoal: "何を求めるために、どの測量を行うのか説明できる。",
    terms: [
      "測量",
      "測点",
      "基準点",
      "既知点",
      "新点",
      "基準点測量",
      "地形測量",
      "応用測量",
    ],
    cautions: [
      "既知点は、点名だけでなく座標系・標高基準・現地の保存状態まで確認します。",
      "新点の値を求めても、所定の手続を経ずに公的な基準点になるわけではありません。",
    ],
    nextLessonId: "distance-and-direction",
    status: "available",
    component: PointAndPositionLesson,
  },
  {
    id: "distance-and-direction",
    number: "02",
    title: "座標・標高・高さの基準",
    description: "同じ地点の座標表現と、標高・楕円体高を支える基準を学ぶ",
    learningGoal:
      "座標値だけでなく、座標系と高さの基準を確認する必要性を説明できる。",
    terms: [
      "緯度",
      "経度",
      "平面直角座標",
      "座標系",
      "原点",
      "系番号",
      "楕円体高",
      "ジオイド高",
      "標高",
      "BM（Benchmark、水準点）",
      "基準点",
    ],
    cautions: [
      "座標値だけでなく、使用する座標系と平面直角座標系の系番号を確認します。",
      "高さの数値だけでなく、楕円体高・標高など高さの基準を確認します。",
      "GNSSで得る楕円体高を、そのまま標高として扱いません。",
      "同一地点の比較では、ジオイド高を地点固有の固定値として考えます。",
      "BMはBenchmark（水準点）を意味し、別種類の点ではありません。",
    ],
    nextLessonId: "height-difference",
    status: "available",
    component: DistanceAndDirectionLesson,
  },
  {
    id: "height-difference",
    number: "03",
    title: "距離測量",
    description: "直接観測する距離を、成果に使う距離へ整える考え方を学ぶ",
    learningGoal:
      "機器が直接測る距離と、成果で使用する距離を区別できる。",
    terms: [
      "水平距離",
      "斜距離",
      "高低差",
      "縮尺",
      "巻尺",
      "レーザー距離計",
      "TS",
      "プリズム",
      "プリズム定数",
      "観測値",
      "補正値",
      "反復観測",
    ],
    cautions: [
      "機器が直接測る値と、計算・補正後に成果で使用する値を区別します。",
      "斜距離を、そのまま水平距離として扱いません。",
      "プリズム定数は、使用する機器とプリズムの組合せを確認します。",
      "温度、張力、気象、傾斜などの観測条件を記録します。",
      "距離の単位と、図面の縮尺を確認します。",
    ],
    nextLessonId: "error-and-equipment",
    status: "available",
    component: HeightDifferenceLesson,
  },
  {
    id: "error-and-equipment",
    number: "04",
    title: "角度・方位角・度分秒",
    description: "角度の基準と回転方向を確認し、方向と2方向間の角を学ぶ",
    learningGoal:
      "北を0度とした方位角と、2方向間の水平角の違いを説明できる。",
    terms: [
      "水平角",
      "方位角",
      "内角",
      "外角",
      "右回り角",
      "左回り角",
      "後視",
      "前視",
      "鉛直角",
      "天頂角",
      "度分秒",
      "十進度",
      "正規化",
    ],
    cautions: [
      "方位角と水平角を混同せず、角度の基準方向を確認します。",
      "北を0度、時計回りを正とする方位角の規約を確認します。",
      "後視方向を設定してから、前視方向を観測します。",
      "右回り・左回りと、内角・外角の定義を確認します。",
      "度分秒の加減算では、秒と分の繰上げ・繰下げを確認します。",
      "鉛直角と天頂角では、0度とする基準方向を確認します。",
    ],
    nextLessonId: "total-station-observation",
    status: "available",
    component: ErrorAndEquipmentLesson,
  },
  {
    id: "total-station-observation",
    number: "05",
    title: "TSの据付と観測",
    description: "据付・方向付け・観測・点検を一連の現場手順として学ぶ",
    learningGoal:
      "TSを据え付けて方向付けし、角度と距離を観測する基本手順を説明できる。",
    terms: [
      "TS",
      "三脚",
      "求心",
      "整準",
      "視度調整",
      "視差",
      "器械高",
      "プリズム高",
      "後視点",
      "前視点",
      "方向付け",
      "水平角",
      "鉛直角",
      "斜距離",
      "点検観測",
      "再観測",
    ],
    cautions: [
      "求心と整準は相互に影響するため、調整後に両方を再確認します。",
      "視度調整と目標への合焦を分けて行い、視差を除去します。",
      "器械高・プリズム高・プリズム定数を測定・確認して記録します。",
      "後視点名、座標、既知方位角、設定した後視方向を照合します。",
      "TSが直接観測する値と、角度・距離・高さから計算する値を区別します。",
      "異常や設定ミスを発見した場合は、影響範囲を確認して再観測を検討します。",
    ],
    nextLessonId: "leveling-basics",
    status: "available",
    component: TotalStationLesson,
  },
  {
    id: "leveling-basics",
    number: "06",
    title: "レベルと水準測量",
    description: "水平な視準線と標尺の読みから、既知標高を新点へつなぐ方法を学ぶ",
    learningGoal:
      "既知標高から後視・前視を使って新点標高を求める流れを説明できる。",
    terms: [
      "レベル",
      "標尺",
      "BM（Benchmark、水準点）",
      "後視",
      "前視",
      "器械高",
      "高低差",
      "転点",
      "TP",
      "往路",
      "復路",
      "閉合",
      "閉合差",
      "視準距離",
      "標尺の鉛直",
      "気泡",
      "自動補正",
      "視差",
    ],
    cautions: [
      "後視と前視は、標尺を置く位置の前後ではなく標高計算上の役割で区別します。",
      "点名、後視、前視、器械高を正しく観測記録へ残します。",
      "転点の標尺は、前視観測を完了する前に動かしません。",
      "標尺を鉛直に保持して読定します。",
      "後視距離と前視距離をできるだけそろえます。",
      "気泡、自動補正機構、視差を観測前に確認します。",
      "閉合差は、適用する作業規程の許容値と比較します。",
      "異常がある場合は原因と影響範囲を確認し、再観測を検討します。",
    ],
    nextLessonId: "observation-error",
    status: "available",
    component: LevelingBasicsLesson,
  },
  {
    id: "observation-error",
    number: "07",
    title: "観測誤差・精度・検査",
    description: "観測値の偏りとばらつきを点検し、成果の採否と再観測を判断する",
    learningGoal:
      "数値が表示されたことと、正しい成果であることは同じではないと説明できる。",
    terms: [
      "真値",
      "基準値",
      "観測値",
      "誤差",
      "正確さ",
      "精密さ",
      "偶然誤差",
      "系統誤差",
      "粗大誤差",
      "残差",
      "平均値",
      "最大最小差",
      "標本標準偏差",
      "誤差伝播",
      "閉合差",
      "許容値",
      "点検",
      "再観測",
    ],
    cautions: [
      "真値は通常完全には分からないため、既知値や点検値を基準として比較します。",
      "正確さと精密さを区別して確認します。",
      "標準偏差が小さいだけで、正確な観測とは判断しません。",
      "平均だけでは、系統誤差や粗大誤差を解決できません。",
      "個々の観測の残差と、路線・観測全体の閉合差を混同しません。",
      "許容値は、測量方法、精度区分、路線長、作業規程により異なります。",
      "許容範囲内でも、原記録、異常値、既知値との比較を確認します。",
      "アンテナ高・器械高・プリズム高、定数、単位、点名の入力を確認します。",
      "異常がある場合は、原因確認、再計算、再観測を行います。",
    ],
    nextLessonId: "coordinate-calculation",
    status: "available",
    component: ObservationErrorLesson,
  },
  {
    id: "coordinate-calculation",
    number: "08",
    title: "座標計算と閉合トラバースへの橋渡し",
    description: "距離と方位角を座標増分へ分解し、新点座標と閉合差へつなげる",
    learningGoal:
      "距離と方位角が、X・Y座標の変化へ分解されることを説明できる。",
    terms: [
      "座標差",
      "距離",
      "方位角",
      "座標増分",
      "緯距",
      "経距",
      "正計算",
      "逆計算",
      "既知点",
      "新点",
      "閉合差",
      "閉合トラバース",
    ],
    cautions: [
      "Xは北方向、Yは東方向、方位角は北を0度として時計回りという規約を確認します。",
      "角度の度と、三角関数へ渡すラジアンを混同しません。",
      "X北・Y東の規約に合わせ、atan2へ渡すΔY・ΔXの順序を確認します。",
      "同一点では距離は0ですが、方位角を一意に定義できません。",
      "計算途中で丸めず、表示するときだけ必要な桁へ丸めます。",
      "座標系や系番号が異なる座標値を直接計算しません。",
      "閉合差が小さいことだけで、観測全体が正しいとは判断しません。",
    ],
    nextLessonId: "field-workflow",
    status: "available",
    component: CoordinateCalculationLesson,
  },
  {
    id: "field-workflow",
    number: "09",
    title: "現場計画・記録・機器管理",
    description: "計画・観測・点検・保存をつなぎ、追跡できる成果を作る流れを学ぶ",
    learningGoal:
      "現場開始前、観測中、終了時に確認すべき項目を説明できる。",
    terms: [
      "作業計画",
      "踏査",
      "既知点",
      "測点",
      "機器点検",
      "観測順序",
      "野帳",
      "観測手簿",
      "現場検算",
      "再測",
      "再計算",
      "観測値",
      "計算値",
      "成果値",
      "データ保存",
      "成果表",
      "安全管理",
    ],
    cautions: [
      "作業目的、成果、適用規程、現場条件を確認してから観測方法と点検方法を計画します。",
      "既知点は点名だけでなく、成果、座標系、高さの基準、現地の保存状態を照合します。",
      "天候、視通、立入条件、交通、地形などの危険を踏査し、現場ごとの安全計画に従います。",
      "点名、機器、設定、器械高・プリズム高、定数、単位、観測条件を原観測値と一緒に記録します。",
      "原記録と生データを計算値や成果値で上書きせず、相互に追跡できる状態で保存します。",
      "異常の原因と影響範囲を確認し、正しい原記録から直せる場合は再計算、観測条件に問題がある場合は再測を検討します。",
      "計算値を自動的に成果値とせず、点検・採用を経て座標系、高さの基準、単位とともに成果表へ示します。",
      "許容値や安全上の作業継続条件は、適用規程、精度区分、現場、機器に応じて確認します。",
    ],
    nextLessonId: null,
    status: "available",
    component: FieldWorkflowLesson,
  },
] as const satisfies readonly BasicsLessonDefinition[];

export type BasicsLesson = (typeof basicsLessons)[number];
export type BasicsLessonId = BasicsLesson["id"];
export type AvailableBasicsLesson = Extract<
  BasicsLesson,
  { readonly status: "available" }
>;
export type AvailableBasicsLessonId = AvailableBasicsLesson["id"];

export const availableBasicsLessons = basicsLessons.filter(
  (lesson): lesson is AvailableBasicsLesson =>
    lesson.status === "available",
);

export const initialBasicsLessonId: AvailableBasicsLessonId =
  basicsLessons[0].id;
